### ISSUE TITLE
Not found config file .apipost

### ISSUE THREAD

**Issue by ShangGuanLiXin** [Apipost-Team/Apipost-idea-plugin#11]
Mac OS 13.3.1
IDEA 2023.1

已配置config
<img width="988" alt="image" src="https://github.com/Apipost-Team/Apipost-idea-plugin/assets/32087402/cfd911f2-a656-4daf-a375-7c013a553191">

点击【Upload To Apipost】时，显示如图信息
<img width="428" alt="image" src="https://github.com/Apipost-Team/Apipost-idea-plugin/assets/32087402/c522b9b4-aacc-4e29-888b-fcffe45061d9">

**Comment by liruizi-rsc** [comment]
> 
你在点击 create config file一下，显示什么呢？填写项目id和token吗？

**Comment by ShangGuanLiXin** [comment]
> 你在点击 create config file一下，显示什么呢？填写项目id和token吗？

是的，但填写完后点击【确定】没什么反应。
<img width="205" alt="image" src="https://github.com/Apipost-Team/Apipost-idea-plugin/assets/32087402/d9ed7b5e-eb99-4705-9499-357116cd70c9">

再次右键选择【Upload To Apipost】时，还是显示
<img width="428" alt="image" src="https://github.com/Apipost-Team/Apipost-idea-plugin/assets/32087402/c522b9b4-aacc-4e29-888b-fcffe45061d9">

**Comment by liruizi-rsc** [comment]
> > 你在点击 create config file一下，显示什么呢？填写项目id和token吗？
> 
> 是的，但填写完后点击【确定】没什么反应。 <img alt="image" width="205" src="https://user-images.githubusercontent.com/32087402/243562717-d9ed7b5e-eb99-4705-9499-357116cd70c9.png">
> 
> 再次右键选择【Upload To Apipost】时，还是显示 <img alt="image" width="428" src="https://user-images.githubusercontent.com/32087402/243181458-c522b9b4-aacc-4e29-888b-fcffe45061d9.png">

重新下载一下 安装再看看

**Comment by ShangGuanLiXin** [comment]
> > > 你在点击 create config file一下，显示什么呢？填写项目id和token吗？
> > 
> > 
> > 是的，但填写完后点击【确定】没什么反应。 <img alt="image" width="205" src="https://user-images.githubusercontent.com/32087402/243562717-d9ed7b5e-eb99-4705-9499-357116cd70c9.png">
> > 再次右键选择【Upload To Apipost】时，还是显示 <img alt="image" width="428" src="https://user-images.githubusercontent.com/32087402/243181458-c522b9b4-aacc-4e29-888b-fcffe45061d9.png">
> 
> 重新下载一下 安装再看看

重新下载插件后，卸载IDEA中的插件，安装新下载的。问题依旧。

**Comment by 1519424054** [comment]
加一，我也遇见这个问题了

**Comment by 1519424054** [comment]
蹲一个解决办法

**Comment by ShangGuanLiXin** [comment]
使用IDEA 市场中下载的插件，已解决该问题。
